# Generated by Django 6.0.3 on 2026-06-01 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blood_glucose',
            field=models.CharField(blank=True, default='95', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood_pressure',
            field=models.CharField(blank=True, default='120/80', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_step_goal',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_water_goal_ml',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='device_id',
            field=models.CharField(blank=True, default='ESP32-RHM-NODE-001', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_primary_contact',
            field=models.CharField(blank=True, default='+254 712 345 678', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_secondary_contact',
            field=models.CharField(blank=True, default='+254 789 012 345', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medical_notes',
            field=models.TextField(blank=True, default='Active treatment baseline. Update allergies and clinical remarks here.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='respiratory_rate',
            field=models.IntegerField(default=16),
        ),
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_contact', models.CharField(max_length=40)),
                ('secondary_contact', models.CharField(blank=True, max_length=40)),
                ('medical_notes', models.TextField(blank=True)),
                ('sms_content', models.TextField()),
                ('status', models.CharField(choices=[('dispatched', 'Dispatched'), ('queued', 'Queued')], default='dispatched', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('weight', 'Weight'), ('water', 'Water')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
