# Generated by Django 6.0.5 on 2026-06-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0009_care_messages_and_triage_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=20, null=True),
        ),
    ]
