# Generated by Django 6.0.6 on 2026-06-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0010_add_gender_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationreminder',
            name='doctor_instructions',
            field=models.TextField(blank=True, help_text='Instructions written by the prescribing doctor'),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='dose_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='doses_taken_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='How many days to take the medicine', null=True),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='prescribing_doctor',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='scheduled_time_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='scheduled_time_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once daily'), ('twice', 'Twice daily'), ('thrice', 'Three times daily'), ('custom', 'Custom')], default='once', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('taken', 'Taken'), ('missed', 'Missed'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
