# Generated by Django 6.0.6 on 2026-06-09 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0011_medication_reminder_schedule_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='spo2',
        ),
        migrations.RemoveField(
            model_name='medicationreminder',
            name='prescribing_doctor',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('wearable', 'Wearable Device')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WearableDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('device_type', models.CharField(choices=[('smartwatch', 'Smartwatch'), ('fitness_tracker', 'Fitness Tracker'), ('thermometer', 'Smart Thermometer'), ('other', 'Other')], default='smartwatch', max_length=30)),
                ('ble_uuid', models.CharField(blank=True, max_length=100)),
                ('is_paired', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='wearable_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records', to='health_app.wearabledevice'),
        ),
    ]
